version: '3.9'

services:

  db:
    container_name: postgresDB
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432